name: 'Dependency Review'
on:
  pull_request:
   types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  dependency-review:
    runs-on: ubuntu-latest 
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high  # Will fail on high and critical severity vulnerabilities
          vulnerability-check: true
          comment-summary-in-pr: on-failure  # Adds a comment only if vulnerabilities are found
          fail-on-scopes: runtime
