name: Static Analysis with CodeQL
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]
env:
  NODE_VERSION: '18.19.0'
jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci --prefer-offline
      # Step 5: Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: typescript
          queries: security-extended
      # Step 6: Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
